### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by Achhhe** [hjynwa/NeurImg-HDR#1]
你好，请问能传一份数据到其他云盘，或者分开打包下载么，目前下载方式总是中断，谢谢啦

**Comment by hjynwa** [comment]
你好！

谢谢你发现的问题，之前一整个压缩包太大了，所以下载总是出错。
我已经更新了数据集的链接，现在应该可以了。

**Comment by hjynwa** [comment]
Dataset link updated.
