### ISSUE TITLE
关于训练的代码

### ISSUE THREAD

**Issue by LLHEVER** [hjynwa/NeurImg-HDR#2]
作者你好，首先非常感谢你们精彩的工作。
最近我也在从事这方面的工作，请问你们可以分享一下训练的代码吗？

**Comment by hjynwa** [comment]
你好，由于该项目涉及与企业的项目合作，因此训练代码不予公开，抱歉。
请直接参考文中的训练细节。

**Comment by hyzhouboy** [comment]
作者你好，你们三年前的工作pami也已经发表了还项目合作不能公开训练代码吗，不知道可否现在开放一下训练代码了？是真的希望能够follow你们的工作，但是没训练代码难以嵌入到不同的视觉任务中，期待。

**Comment by jinhan-sony** [comment]
同学你好，谢谢你的关注！
该项目与企业合作是在2021年秋交付，合作项目有2年的保密时效，请理解。
我们近期准备release训练代码了，到时候会在issue通知，谢谢！

**Comment by hjynwa** [comment]
同学你好，谢谢你的关注！
该项目与企业合作是在2021年秋交付，合作项目有2年的保密时效，请理解。
我们近期准备release训练代码了，到时候会在issue通知，谢谢！

**Comment by hjynwa** [comment]
同学你好，网络的训练代码已经release了，可以试试看。
如有任何问题，随时联系。
谢谢！
