### ISSUE TITLE
Tone mapping problem

### ISSUE THREAD

**Issue by LiuHgy** [hjynwa/NeurImg-HDR#3]
Hello,I have a problem when I run the tone mapping command:
> sh: 1: luminance-hdr-cli: not found

I have used this command `python test.py --dataroot datasets/spike_video_dataset --im_type spike --dataset_mode test --model video --name spike_video --netColor video` to generate .exr files.But when I use the tone mapping command `python reinhard_tonemap.py` the above information will appear.And the tone-mapping picture will not generate.

**Comment by hjynwa** [comment]
Please install luminance-hdr-cli using 'apt' in Linux.

**Comment by LiuHgy** [comment]
Thanks.

**Comment by ice-cream567** [comment]
> 谢谢。

May I ask which version of Ubuntu you are using? I tried to execute sudo apt install luminance-hdr-cli on 22.04 and 18.04 but failed. I could only execute sudo apt install luminance-hdr.
