### ISSUE TITLE
Unable to locate package luminance-hdr-cli

### ISSUE THREAD

**Issue by ice-cream567** [hjynwa/NeurImg-HDR#4]
Hello, when I execute python reinhard_tonemap.py -i spike_video, the error luminance-hdr-cli: not found appears; when I execute sudo apt install luminance-hdr-cli, the prompt:

Reading package list... Done
Analyzing a package's dependency tree
Reading status information... Complete
E: Unable to locate package luminance-hdr-cli

Run the program again after executing sudo apt install luminance-hdr (python reinhard_tonemap.py -i spike_video) error:

I18NDIR: /usr/share/luminance-hdr/i18n
ERROR: unrecognized option '-G'

  33%|##############6 | 1/3 [00:00<00:00, 9.44it/s]I18NDIR: /usr/share/luminance-hdr/i18n
ERROR: unrecognized option '-G'

I18NDIR: /usr/share/luminance-hdr/i18n
ERROR: unrecognized option '-G'

I tried it on ubuntu22.04 and 18.04 versions, but neither solved the problem.
Could you please help me solve it?

**Comment by hjynwa** [comment]
Have you tried to update your apt packages?

**Comment by ice-cream567** [comment]
Yes, I tried. But the problem remains. Is this problem related to the ubuntu version?
&nbsp;


两点水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SONG, ***@***.***&gt;; 
发送时间: 2024年4月3日(星期三) 上午9:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hjynwa/NeurImg-HDR] Unable to locate package luminance-hdr-cli (Issue #4)















你试过更新你的apt软件包吗？

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:< hjynwa /新基金-人类发展报告/问题/ 4 / ***@***.***和&gt;

**Comment by hjynwa** [comment]
Maybe you should try`sudo apt-get install luminance-hdr` instead of `luminance-hdr-cli`.
